# Generated by Django 4.2.7 on 2024-09-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155)),
                ("author", models.CharField(max_length=155)),
                ("published_date", models.DateField(auto_now_add=True)),
                ("isbn", models.CharField(max_length=155)),
                ("page_count", models.IntegerField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("Русский", "Русский"),
                            ("Английский", "Английский"),
                            ("Француский", "Француский"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Книги",
            },
        ),
    ]
